### ISSUE TITLE
vs2015编译cef_module 报错  fatal error C1049: 无效的数值参数“specload”

### ISSUE THREAD

**Issue by hczhouu** [netease-im/NIM_PC_UIKit#13]
vs2015编译cef_module报错  fatal error C1049: 无效的数值参数“specload”
命令行也没有specload这个参数 。。。

**Comment by nmgwddj** [comment]
CEF 相关模块的维护我们已经移植到开源的 duilib 仓库，请参考这里代码：https://github.com/netease-im/NIM_Duilib_Framework
